image:
  repository: 298717586040.dkr.ecr.us-east-1.amazonaws.com/troubleshoot-eks-131-app
  tag: "sha-0605970"
replicaCount: 2

securityContext:
  runAsNonRoot: true
  runAsUser: 10001
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop: ["ALL"]

writablePaths:
  - name: tmp
    mountPath: /app/tmp
