apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: services-web-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minhajlhq/EKS.git
    targetRevision: main
    path: services-web/chart
    helm:
      valueFiles:
        - ../../gitops-argocd/envs/dev/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: demo
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
