apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "services-web.fullname" . }}
  labels: {{- include "services-web.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "services-web.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "services-web.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.extraEnvFrom }}
          envFrom:
{{ toYaml .Values.extraEnvFrom | indent 12 }}
{{- end }}
{{- if .Values.extraEnv }}
          env:
{{ toYaml .Values.extraEnv | indent 12 }}
{{- end }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          resources: {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          securityContext:
            readOnlyRootFilesystem: {{ .Values.securityContext.readOnlyRootFilesystem }}
            allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
            capabilities:
              drop:
              {{- range .Values.securityContext.capabilities.drop }}
                - {{ . }}
              {{- end }}
          volumeMounts:
            {{- range .Values.writablePaths }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
            {{- end }}
      volumes:
        {{- range .Values.writablePaths }}
        - name: {{ .name }}
          emptyDir: {}
        {{- end }}